"""
### CODE OWNERS: Shea Parkes, Kyle Baird

### OBJECTIVE:
  Stage data drive folders for postboarding work.

### DEVELOPER NOTES:
  This also code-gens a simple SAS script as well.
"""
import os
import re
import datetime
import json

from pathlib import Path


# =============================================================================
# LIBRARIES, LOCATIONS, LITERALS, ETC. GO ABOVE HERE
# =============================================================================


def get_path_current():
    """Determine the path of this file"""
    try:
        return Path(os.path.realpath(__file__)).parent
    except NameError:
        # Likely running interactively
        return Path.cwd()

class NotAPostModuleException(Exception):
    """Custom exception to allow graceful control flow handling"""
    pass


class PostboardModule(object):
    """Represents a postboarding module"""

    def __init__(self, path_module, path_data_root):
        self.path_obj = path_module
        self.path_data_root = path_data_root
        self.path_data = self.path_data_root / self.path_obj.name

        if not self.path_obj.is_dir():
            raise NotAPostModuleException('{} is not a folder'.format(self.path_obj))

        prefix_match = re.match(
            r'Post\d{3}',
            self.path_obj.name,
            re.IGNORECASE,
            )

        if not prefix_match:
            raise NotAPostModuleException('{} does not start with "Post###"'.format(self.path_obj))

        self.abbreviation = prefix_match.group(0).lower()

    def make_data_dir(self):
        """Make the module's data dir if appropriate"""
        try:
            self.path_data.mkdir()
        except FileExistsError:
            pass

    def codegen_sas_macro_variable(self):
        """Generate SAS code that will create an appropriate macro variable"""
        return r'%let {} = {}{};'.format(
            self.abbreviation,
            self.path_data,
            os.sep,
            )

    def create_module_path_dict(self):
        """Return trivial dict describing this module's location"""
        return {self.abbreviation: str(self.path_data)}

    def __repr__(self):
        return '\n'.join([
            '',
            'PostBoarding Module Path is {}'.format(self.path_obj),
            'Abbreviation is {}'.format(self.abbreviation),
            ])



if __name__ == '__main__':
    import prm.meta.project
    PRM_META = prm.meta.project.parse_project_metadata()
    import sys
    sys.path.append(str(PRM_META[10, 'code'] / 'healthbi_driver'))

    # Rebuild all basic folders (especially local module folders)
    from driver import Driver

    driver_ = Driver(
        project_id=PRM_META['project_id'],
        deliverable_name=PRM_META['deliverable_name'],
        project_namespace=PRM_META['project_namespace'],
        prod_input=os.path.join(
            str(
                PRM_META['path_project']
            ),
            'driver.json',
            ),
        )
    driver_.create_folders()

    # Move on to making postboarding folders
    PATH_PROJECT_DATA = PRM_META['path_project_data'] / 'postboarding'
    try:
        PATH_PROJECT_DATA.mkdir()
    except FileExistsError:
        pass

    PATH_CURRENT = get_path_current()

    PATH_SAS_SETUP = PATH_PROJECT_DATA / 'postboarding_libraries.sas'
    PATH_JSON_OUT = PATH_PROJECT_DATA / 'postboarding_directories.json'

    POSTBOARDING_DIRS = dict()

    print('BEGINNING GENERATION OF {}\n\n'.format(PATH_SAS_SETUP))
    with PATH_SAS_SETUP.open('w') as fh_codegen:

        fh_codegen.write('/*Code generated by {} by user {} on {}*/\n\n'.format(
            PATH_CURRENT,
            os.environ['UserName'],
            datetime.datetime.now(),
            ))

        fh_codegen.write('%let path_postboarding_data_root = {}{};\n'.format(
            str(PATH_PROJECT_DATA),
            os.sep,
            ))

        print('BEGINNING SCAN OF {}\n\n'.format(PATH_CURRENT))
        for path_ in PATH_CURRENT.iterdir():
            try:
                mod_ = PostboardModule(path_, PATH_PROJECT_DATA)
                print(mod_)
                mod_.make_data_dir()
                fh_codegen.write('\n{}\n'.format(mod_.codegen_sas_macro_variable()))
                POSTBOARDING_DIRS.update(mod_.create_module_path_dict())
            except NotAPostModuleException as exception:
                print('\n{}\n'.format(exception.args[0]))

    print('\n\nFINISHED GENERATION OF {}\n\n'.format(PATH_SAS_SETUP))

    print('BEGINNING GENERATION OF {}\n\n'.format(PATH_JSON_OUT))
    with PATH_JSON_OUT.open("w") as fh_json:
        json.dump(
            POSTBOARDING_DIRS,
            fh_json,
            sort_keys=True,
            indent=4,
            )
    print('\n\nFINISHED GENERATION OF {}\n\n'.format(PATH_JSON_OUT))
